# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Some algorithm', max_length=20)),
                ('train_parameters', models.FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Some dataset', max_length=20)),
                ('frequency', models.CharField(choices=[(b'daily', b'daily'), (b'minute', b'minute')], default=b'daily', max_length=6)),
            ],
        ),
    ]
