# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algotesting', '0006_algorithm_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(default=b'Some dataset', max_length=20, unique=True),
        ),
    ]
