# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algotesting', '0009_auto_20160428_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='algorithm',
            field=models.FileField(default=b'', upload_to=b'algorithms/'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
