# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algotesting', '0010_auto_20160428_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(default=b'')),
                ('results', models.FileField(default=b'', upload_to=b'testing/results/')),
            ],
        ),
    ]
