# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algotesting', '0011_experimentresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentresult',
            name='results',
        ),
        migrations.AddField(
            model_name='experimentresult',
            name='results_path',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
