# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algotesting', '0014_auto_20160429_0727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['-name']},
        ),
    ]
