# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algotesting', '0015_auto_20160429_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['name']},
        ),
    ]
