# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algotesting', '0016_auto_20160429_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(default=b'', max_length=20, unique=True),
        ),
    ]
