# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algotesting', '0017_auto_20160507_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='filename',
            field=models.CharField(default=b'', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='filename',
            field=models.CharField(default=b'', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(default=b'Some algorithm', max_length=20),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(default=b'Some dataset', max_length=20),
        ),
    ]
