# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-07 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algotesting', '0018_auto_20160507_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='date_format',
            field=models.CharField(blank=True, default=b'', max_length=50),
        ),
    ]
