# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-14 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algotesting', '0019_auto_20160507_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentresult',
            name='profit',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experimentresult',
            name='test_results',
            field=models.TextField(default=b''),
        ),
    ]
