# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-15 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algotesting', '0020_auto_20160514_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='filename',
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_filenames',
            field=models.CharField(default=b'', max_length=300),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='columns',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(default=b'Dataset', max_length=30, unique=True),
        ),
    ]
