# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algotesting', '0021_auto_20160515_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={},
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(default=b'Dataset', max_length=50, unique=True),
        ),
    ]
